// gen-unlock-rules.mts — THE UNLOCK RULEBOOK, read off an achievements dump and committed.
//
// WHY A COMMITTED FILE. The requirements of a race, class or deity unlock are the game's rules,
// the same for every character, and the only place they are written down is the `Untapped
// Potential` groups of a `/outputfile achievements` dump. A player who has never exported one
// still has a Loot page, a mob page and a Factions table, and each of those wants to say "this is
// on the way to Kerran". So the rules travel with the app, and a character's own dump supplies
// only what it alone can: which lines the server marks done.
//
// Run: `npx tsx scripts/gen-unlock-rules.mts [dump]`. The default dump is the committed fixture,
// which holds every one of the 16 races, 16 classes and 17 deities. A dump with fewer (a newer
// one printed with Complete unticked in the window) would write a shorter rulebook, so the
// script refuses one that lists fewer unlocks than the file it would replace.

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { achievementBook } from '../src/shared/outputs/achievementBook'
import { parseAchievementsDump } from '../src/shared/outputs/achievements'
import { unlockBook, type Unlock } from '../src/shared/unlocks/unlocks'
import { UNLOCK_RULES, type UnlockRule } from '../src/shared/unlocks/unlockRules.generated'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DEFAULT_DUMP = join(ROOT, 'tests', 'fixtures', 'Primitive_freeport-Achievements.txt')
const OUT = join(ROOT, 'src', 'shared', 'unlocks', 'unlockRules.generated.ts')

function rule(u: Unlock): UnlockRule {
  return {
    kind: u.kind,
    name: u.name,
    needs: u.needs.map((n) => ({ kind: n.kind, subject: n.subject, text: n.text }))
  }
}

const dumpPath = resolve(process.argv[2] ?? DEFAULT_DUMP)
if (!existsSync(dumpPath)) throw new Error(`no such dump: ${dumpPath}`)
const book = unlockBook(achievementBook(parseAchievementsDump(readFileSync(dumpPath, 'utf8'))))
const rules = [...book.races, ...book.classes, ...book.deities].map(rule)
if (rules.length < UNLOCK_RULES.length) {
  throw new Error(
    `${dumpPath} lists ${String(rules.length)} unlocks; the committed rulebook has ${String(UNLOCK_RULES.length)}. A dump printed with Complete unticked leaves finished unlocks out - export with Open and Complete both shown.`
  )
}

const source = dumpPath.startsWith(ROOT)
  ? dumpPath.slice(ROOT.length + 1).replace(/\\/g, '/')
  : dumpPath
const text = `// GENERATED by scripts/gen-unlock-rules.mts from ${source} - do not edit by hand.
//
// The requirement lines of every race, class and deity unlock, as the game states them in the
// \`Untapped Potential\` groups of an achievements dump. See the generator for why they are
// committed and shared/unlocks/unlockGraph.ts for how they are read.

import type { NeedKind, UnlockKind } from './unlocks'

export interface RuleNeed {
  kind: NeedKind
  /** the faction, the item or the task title; the whole line otherwise */
  subject: string
  text: string
}

export interface UnlockRule {
  kind: UnlockKind
  name: string
  needs: RuleNeed[]
}

// prettier-ignore
export const UNLOCK_RULES: readonly UnlockRule[] = [
${rules.map((r) => `  ${JSON.stringify(r)}`).join(',\n')}
]
`
writeFileSync(OUT, text.replace(/\n/g, '\r\n'))
console.log(`wrote ${OUT}: ${String(rules.length)} unlocks from ${source}`)
